In [1]:
import pandas as pd
import numpy as np

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [2]:
df = pd.read_csv("C:\\Users\\mitta\\OneDrive\\Desktop\\ML\\Data Set\\covid_toy - covid_toy.csv")

In [3]:
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [4]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [5]:
from sklearn.model_selection import train_test_split

x_train , x_test , y_train , y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [6]:
x_train

    age  gender  fever   cough       city
81   65    Male   99.0    Mild      Delhi
0    60    Male  103.0    Mild    Kolkata
62   56  Female  104.0  Strong  Bangalore
68   54  Female  104.0  Strong    Kolkata
50   19    Male  101.0    Mild      Delhi
..  ...     ...    ...     ...        ...
9    64  Female  101.0    Mild      Delhi
93   27    Male  100.0    Mild    Kolkata
71   75  Female  104.0  Strong      Delhi
10   75  Female    NaN    Mild      Delhi
48   66    Male   99.0  Strong  Bangalore

[80 rows x 5 columns]

In [7]:
si = SimpleImputer(strategy= "mean")
x_train_fever = si.fit_transform(x_train[['fever']])

# also the test test data
x_test_fever = si.fit_transform(x_test[['fever']])

x_train_fever.shape

(80, 1)

In [8]:
# ordinal encoding
oe = OrdinalEncoder(categories=[['Mild' , 'Strong']])
x_train_cough = oe.fit_transform(x_train[['cough']])

x_train_cough.shape

(80, 1)

In [9]:
# One hot Encoding --> gender , city

ohe = OneHotEncoder(drop = 'first' , sparse_output= False)
x_train_gender_city = ohe.fit_transform(x_train[['gender','city']])

x_test_gender_city = ohe.fit_transform(x_test[['gender','city']])

x_train_gender_city.shape

(80, 4)

In [10]:
# extracting age
x_train_age = x_train.drop(columns = 
                           ['gender','fever','cough','city']).values

x_test_age = x_test.drop(columns = 
                         ['gender','fever','cough','city']).values

In [11]:
x_train_age.shape

(80, 1)

In [12]:
import numpy as np

x_train_transformed = np.concatenate(
    (x_train_age, x_train_fever, x_train_gender_city, x_train_cough),
    axis=1
)

In [13]:
x_train_transformed.shape

(80, 7)

In [14]:
# BY THE HELP OF COLUMNS TRANSFORMER

In [15]:
x_train

    age  gender  fever   cough       city
81   65    Male   99.0    Mild      Delhi
0    60    Male  103.0    Mild    Kolkata
62   56  Female  104.0  Strong  Bangalore
68   54  Female  104.0  Strong    Kolkata
50   19    Male  101.0    Mild      Delhi
..  ...     ...    ...     ...        ...
9    64  Female  101.0    Mild      Delhi
93   27    Male  100.0    Mild    Kolkata
71   75  Female  104.0  Strong      Delhi
10   75  Female    NaN    Mild      Delhi
48   66    Male   99.0  Strong  Bangalore

[80 rows x 5 columns]

In [16]:
from sklearn.compose import ColumnTransformer

transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),

    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),

    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])

],remainder='passthrough')

In [ ]:
# APPLYING ON THE INSURANCE DATSET 

import pandas as pd
import numpy as np

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [18]:
df = pd.read_csv("C:\\Users\\mitta\\OneDrive\\Desktop\\ML\\Data Set\\insurance - insurance.csv")
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [19]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [20]:
df = df.drop_duplicates()

In [21]:
x = df.drop(columns = 'charges')
y = df['charges']

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
x_train , x_test , y_train , y_test = train_test_split(df.drop(columns=['charges']),df['charges'],test_size=0.2)

In [24]:
x_train

      age     sex     bmi  children smoker     region
57     18    male  31.680         2    yes  southeast
1175   22  female  27.100         0     no  southwest
1253   40  female  29.300         4     no  southwest
403    49    male  32.300         3     no  northwest
149    19    male  28.400         1     no  southwest
...   ...     ...     ...       ...    ...        ...
784    31  female  29.260         1     no  southeast
749    28    male  30.875         0     no  northwest
1071   63    male  31.445         0     no  northeast
699    23  female  39.270         2     no  southeast
668    62    male  32.015         0    yes  northeast

[1069 rows x 6 columns]

In [25]:
from sklearn.compose import ColumnTransformer

transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['bmi']),

    ('tnf2',OrdinalEncoder(categories=[['yes','no']]),['smoker']),

    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['sex','region'])

],remainder='passthrough')

In [26]:
transformer.fit_transform(x_train).shape

(1069, 8)

In [27]:
import pandas as pd
import numpy as np

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [28]:
df = pd.read_csv("C:\\Users\\mitta\\OneDrive\\Desktop\\ML\\Data Set\\tips - tips.csv")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [29]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [30]:
df = df.drop_duplicates()

In [31]:
df = df.drop_duplicates()

In [32]:
x = df.drop(columns = 'total_bill')
y = df['total_bill']

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
x_train , x_test , y_train , y_test = train_test_split(df.drop(columns=['total_bill']),df['total_bill'],test_size=0.2)

In [35]:
x_train

      tip     sex smoker   day    time  size
169  2.00  Female    Yes   Sat  Dinner     2
99   1.50    Male     No   Fri  Dinner     2
33   2.45  Female     No   Sat  Dinner     4
101  3.00  Female    Yes   Fri  Dinner     2
98   3.00    Male    Yes   Fri  Dinner     2
..    ...     ...    ...   ...     ...   ...
138  2.00    Male    Yes  Thur   Lunch     2
233  1.47    Male     No   Sat  Dinner     2
159  2.00    Male     No   Sun  Dinner     4
120  2.31    Male     No  Thur   Lunch     2
175  3.11    Male    Yes   Sun  Dinner     2

[194 rows x 6 columns]

In [36]:
from sklearn.compose import ColumnTransformer

transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['tip']),

('tnf2', OrdinalEncoder(categories=[['No','Yes']]), ['smoker']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['sex','day'])

],remainder='passthrough')

In [37]:
transformer.fit_transform(x_train).shape

(194, 8)