## 31/03/2026

In [1]:
# Machine Learning
# data (50) = x(input data ) , y(target data )
# x --> x_train , x_test 
# y --> y_train , y_test
# for machine learning we will pass (x_train) , (x_test)
# for machine learning (x_test) --> y_pred

In [2]:
# 1+1 = 2
# 1+2 = 3
# 1+3 = 4
# 1+4 = 5
# 1+5 = 6

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("Data Set\covid_toy - covid_toy.csv")
df.head()

<>:1: SyntaxWarning: "\c" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\c"? A raw string is also an option.
<>:1: SyntaxWarning: "\c" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\c"? A raw string is also an option.
C:\Users\mitta\AppData\Local\Temp\ipykernel_11708\2352704592.py:1: SyntaxWarning: "\c" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\c"? A raw string is also an option.
  df = pd.read_csv("Data Set\covid_toy - covid_toy.csv")

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [5]:
df.shape

(100, 6)

In [6]:
# finding null values 

df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [7]:
df['fever'] = df['fever'].fillna(df['fever'].mean())

In [8]:
# df.isnull().sum()

In [9]:
x = df.drop(columns=['has_covid'])  # Input data

In [10]:
y = df['has_covid'] # target or output data 
y

0      No
1     Yes
2      No
3      No
4      No
     ...
95     No
96    Yes
97     No
98     No
99    Yes
Name: has_covid, Length: 100, dtype: str

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2 , random_state= 42)

In [ ]:
print("total data shape" , df.shape)
print("------------------------------")
print("input data shape " , x.shape)
print("x_train data shape ",x_train.shape)
print("x_test_data_shape ", x_test.shape)
print("-------------------------------")
print("target data shape" , y.shape)
print("y_train data shape ",y_train.shape)
print("y_test_data_shape ", y_test.shape)

total data shape (100, 6)
------------------------------
input data shape  (100, 5)
x_train data shape  (80, 5)
x_test_data_shape  (20, 5)
-------------------------------
target data shape (100,)
y_train data shape  (80,)
y_test_data_shape  (20,)

In [14]:
import pandas as pd

# 1. Load dataset
df = pd.read_csv("Data Set\covid_toy - covid_toy.csv")   # make sure file name is correct
df.head()

<>:4: SyntaxWarning: "\c" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\c"? A raw string is also an option.
<>:4: SyntaxWarning: "\c" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\c"? A raw string is also an option.
C:\Users\mitta\AppData\Local\Temp\ipykernel_11708\1571681003.py:4: SyntaxWarning: "\c" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\c"? A raw string is also an option.
  df = pd.read_csv("Data Set\covid_toy - covid_toy.csv")   # make sure file name is correct

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [15]:
df.shape

(100, 6)

In [16]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [17]:
df.columns

Index(['age', 'gender', 'fever', 'cough', 'city', 'has_covid'], dtype='str')

In [18]:
x = df[['age', 'fever']]
y = df['has_covid']

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2 , random_state= 42)

In [21]:
print("total data shape" , df.shape)
print("------------------------------")
print("input data shape " , x.shape)
print("x_train data shape ",x_train.shape)
print("x_test_data_shape ", x_test.shape)
print("-------------------------------")
print("target data shape" , y.shape)
print("y_train data shape ",y_train.shape)
print("y_test_data_shape ", y_test.shape)

total data shape (100, 6)
------------------------------
input data shape  (100, 2)
x_train data shape  (80, 2)
x_test_data_shape  (20, 2)
-------------------------------
target data shape (100,)
y_train data shape  (80,)
y_test_data_shape  (20,)