## 08 - 04 - 2026

In [84]:
# Encoding -->  transform your categorical data to numerical data .

In [85]:
# label encoder --> has_covid['Yes' , 'No'] --> encode --> has_covid[1,0]

In [86]:
import pandas as pd
import numpy as np

In [87]:
df = pd.read_csv("Data Set\covid_toy - covid_toy.csv")
df.head()

<>:1: SyntaxWarning: "\c" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\c"? A raw string is also an option.
<>:1: SyntaxWarning: "\c" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\c"? A raw string is also an option.
C:\Users\mitta\AppData\Local\Temp\ipykernel_12744\2352704592.py:1: SyntaxWarning: "\c" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\c"? A raw string is also an option.
  df = pd.read_csv("Data Set\covid_toy - covid_toy.csv")

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [88]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [89]:
df = df.dropna()

In [90]:
from sklearn.preprocessing import LabelEncoder

In [91]:
lb = LabelEncoder()

In [92]:
df['city'].value_counts()

city
Kolkata      29
Bangalore    28
Delhi        20
Mumbai       13
Name: count, dtype: int64

In [93]:
df['gender'] = lb.fit_transform(df['gender'])
df['cough'] = lb.fit_transform(df['cough'])
df['city'] = lb.fit_transform(df['city'])
df['has_covid'] = lb.fit_transform(df['has_covid'])

In [94]:
df.head()

   age  gender  fever  cough  city  has_covid
0   60       1  103.0      0     2          0
1   27       1  100.0      0     1          1
2   42       1  101.0      0     1          0
3   31       0   98.0      0     2          0
4   65       0  101.0      0     3          0

In [95]:
x = df.drop(columns= ['has_covid'])
y = df['has_covid']

In [96]:
from sklearn.model_selection import train_test_split

In [97]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2, random_state= 42 )

In [98]:
## Apply standardisation for coverting my data into normal distribution

In [99]:
from sklearn.preprocessing import StandardScaler

In [100]:
sc = StandardScaler()

In [101]:
x_train_sc = sc.fit_transform(x_train)

In [102]:
x_train_new = pd.DataFrame(x_train_sc , columns= x_train.columns)

In [103]:
np.round(x_train_new.describe() , 2)

         age  gender  fever  cough   city
count  72.00   72.00  72.00  72.00  72.00
mean   -0.00   -0.00  -0.00   0.00   0.00
std     1.01    1.01   1.01   1.01   1.01
min    -1.53   -0.75  -1.30  -0.73  -1.20
25%    -0.95   -0.75  -0.83  -0.73  -1.20
50%     0.14   -0.75   0.13  -0.73  -0.24
75%     0.86    1.33   0.72   1.37   0.72
max     1.57    1.33   1.55   1.37   1.69

In [104]:
import pandas as pd 
import numpy as np

In [105]:
df = pd.read_csv("C:\\Users\\mitta\\OneDrive\\Desktop\\ML\\Data Set\\tips - tips.csv")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [106]:
df = df.dropna()

In [107]:
from sklearn.preprocessing import LabelEncoder

In [108]:
lb = LabelEncoder()

In [109]:
df['sex'] = lb.fit_transform(df['sex'])
df['smoker'] = lb.fit_transform(df['smoker'])
df['day'] = lb.fit_transform(df['day'])
df['time'] = lb.fit_transform(df['time'])

In [110]:
df.head()

   total_bill   tip  sex  smoker  day  time  size
0       16.99  1.01    0       0    2     0     2
1       10.34  1.66    1       0    2     0     3
2       21.01  3.50    1       0    2     0     3
3       23.68  3.31    1       0    2     0     2
4       24.59  3.61    0       0    2     0     4

In [111]:
x = df.drop(columns = ['total_bill'])
y = df['total_bill']

In [112]:
from sklearn.model_selection import train_test_split

In [113]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2 , random_state=42)

In [114]:
from sklearn.preprocessing import MinMaxScaler

In [115]:
mn = MinMaxScaler()

In [116]:
x_train_mn = mn.fit_transform(x_train)

In [117]:
x_train_new = pd.DataFrame(x_train_mn , columns = x_train.columns)

In [118]:
np.round(x_train_new.describe() , 2)

          tip     sex  smoker     day    time    size
count  195.00  195.00  195.00  195.00  195.00  195.00
mean     0.23    0.65    0.38    0.57    0.27    0.31
std      0.16    0.48    0.49    0.31    0.45    0.19
min      0.00    0.00    0.00    0.00    0.00    0.00
25%      0.11    0.00    0.00    0.33    0.00    0.20
50%      0.22    1.00    0.00    0.67    0.00    0.20
75%      0.30    1.00    1.00    0.67    1.00    0.40
max      1.00    1.00    1.00    1.00    1.00    1.00

In [119]:
import pandas as pd 
import numpy as np

In [122]:
df = pd.read_csv("C:\\Users\\mitta\\OneDrive\\Desktop\\ML\\Data Set\\insurance - insurance.csv")
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [123]:
df = df.dropna()

In [124]:
from sklearn.preprocessing import LabelEncoder

In [125]:
lb = LabelEncoder()

In [126]:
df['sex'] = lb.fit_transform(df['sex'])
df['smoker'] = lb.fit_transform(df['smoker'])
df['region'] = lb.fit_transform(df['region'])

In [127]:
df.head()

   age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       3  16884.92400
1   18    1  33.770         1       0       2   1725.55230
2   28    1  33.000         3       0       2   4449.46200
3   33    1  22.705         0       0       1  21984.47061
4   32    1  28.880         0       0       1   3866.85520

In [128]:
x = df.drop(columns = ['charges'])
y = df['charges']

In [129]:
from sklearn.model_selection import train_test_split

In [130]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size= 0.2 , random_state=42)

In [131]:
from sklearn.preprocessing import StandardScaler

In [132]:
sc = StandardScaler()

In [133]:

x_train_sc = sc.fit_transform(x_train)

In [134]:
x_train_new = pd.DataFrame(x_train_sc , columns = x_train.columns)

In [137]:
np.round(x_train_new.describe(),2)

           age      sex      bmi  children   smoker   region
count  1070.00  1070.00  1070.00   1070.00  1070.00  1070.00
mean     -0.00    -0.00    -0.00     -0.00     0.00    -0.00
std       1.00     1.00     1.00      1.00     1.00     1.00
min      -1.52    -1.02    -2.42     -0.91    -0.51    -1.35
25%      -0.88    -1.02    -0.72     -0.91    -0.51    -0.46
50%       0.01     0.98    -0.06     -0.09    -0.51     0.44
75%       0.83     0.98     0.65      0.73    -0.51     0.44
max       1.75     0.98     3.74      3.20     1.97     1.34