# 07-04-2026

In [1]:
# normalization --> using minmaxscaling
# data Min_value = 0 , Max_value = 1

In [2]:
import pandas as pd 
import numpy as np

In [3]:
df = pd.read_csv("c:\\Users\\mitta\\OneDrive\\Desktop\\DATASET\\data_set\\covid_toy - covid_toy.csv")
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [4]:
df['fever'] = df['fever'].fillna(df['fever'].mean())

In [5]:
df['gender'] = df['gender'].map({"Male" : 0 , 'Female' : 1})
df['has_covid'] = df['has_covid'].map({'Yes':1 , 'No':0})
df['cough'] = df['cough'].map( {"Mild" : 0 , 'Strong': 1 })

In [6]:
df = df.drop(columns=['city'])

In [7]:
x = df.drop(columns=['has_covid'])
y = df['has_covid']

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2 , random_state= 42)

In [10]:
np.round(x_train.describe(),2)

         age  gender   fever  cough
count  80.00   80.00   80.00  80.00
mean   42.91    0.59  100.98   0.40
std    24.47    0.50    1.93   0.49
min     5.00    0.00   98.00   0.00
25%    20.00    0.00  100.00   0.00
50%    42.00    1.00  101.00   0.00
75%    65.00    1.00  102.00   1.00
max    84.00    1.00  104.00   1.00

In [11]:
from sklearn.preprocessing import MinMaxScaler

In [12]:
mn = MinMaxScaler()

In [13]:
x_train_mn = mn.fit_transform(x_train)

In [14]:
x_train_new = pd.DataFrame(x_train_mn , columns = x_train.columns )

In [15]:
np.round(x_train_new.describe(),2)

         age  gender  fever  cough
count  80.00   80.00  80.00  80.00
mean    0.48    0.59   0.50   0.40
std     0.31    0.50   0.32   0.49
min     0.00    0.00   0.00   0.00
25%     0.19    0.00   0.33   0.00
50%     0.47    1.00   0.50   0.00
75%     0.76    1.00   0.67   1.00
max     1.00    1.00   1.00   1.00

In [ ]:
# ------------------------------------------------------------------------------------------------

In [16]:
import pandas as pd 
import numpy as np

In [17]:
df = pd.read_csv("c:\\Users\\mitta\\OneDrive\\Desktop\\DATASET\\data_set\\placement - placement.csv")
df.head()

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1
4  7.52          7.30       1

In [18]:
df.isnull().sum()

cgpa            0
resume_score    0
placed          0
dtype: int64

In [19]:
x = df.drop(columns=['placed'])
y = df['placed']

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2 , random_state= 42)

In [22]:
np.round(x_train.describe(),2)

        cgpa  resume_score
count  80.00         80.00
mean    6.95          7.00
std     1.13          1.01
min     5.27          4.95
25%     6.00          6.28
50%     6.62          7.15
75%     8.06          7.69
max     9.31          9.06

In [23]:
from sklearn.preprocessing import MinMaxScaler

In [24]:
mn = MinMaxScaler()

In [25]:
x_train_mn = mn.fit_transform(x_train)

In [26]:
x_train_new = pd.DataFrame(x_train_mn , columns = x_train.columns )

In [27]:
np.round(x_train_new.describe(),2)

        cgpa  resume_score
count  80.00         80.00
mean    0.42          0.50
std     0.28          0.25
min     0.00          0.00
25%     0.18          0.32
50%     0.33          0.54
75%     0.69          0.67
max     1.00          1.00